version: "3.8"

x-base: &base
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - "./storage:/var/www/html/storage"

x-web-base: &web-base
    <<: *base
    networks:
        - web_network
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 3

x-worker-base: &worker-base
    <<: *base
    networks:
        - worker_network
    stop_signal: SIGTERM
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 3

services:
    app:
        <<: *web-base
        healthcheck:
            test: ["CMD", "php", "artisan", "health:check"]

    task:
        <<: *worker-base
        command: ["php", "/var/www/html/artisan", "schedule:work"]
        healthcheck:
            test: ["CMD", "healthcheck-schedule"]
            start_period: 10s

    queue:
        <<: *worker-base
        command: ["php", "/var/www/html/artisan", "queue:work", "--sleep=3", "--tries=3", "--max-time=3600"]
        healthcheck:
            test: ["CMD", "healthcheck-queue"]
            start_period: 10s
        environment:
            PHP_FPM_POOL_NAME: app_queue

    financial_transactions_queue:
        <<: *worker-base
        command:
            - php
            - /var/www/html/artisan
            - queue:work
            - --queue=bank-connection
            - --tries=3
            - --max-time=3600
            - --backoff=60
        healthcheck:
            test: ["CMD", "healthcheck-queue"]
            start_period: 10s
        environment:
            PHP_FPM_POOL_NAME: financial_transactions_queue

    ssr:
        <<: *web-base
        command: ["php", "/var/www/html/artisan", "inertia:start-ssr", "--runtime=bun"]
        ports:
            - "13714:13714"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:13714/health"]
        environment:
            PHP_FPM_POOL_NAME: app_ssr

networks:
    web_network:
        driver: bridge
    worker_network:
        driver: bridge
