services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./storage:/var/www/html/storage"
        environment:
            - AUTORUN_ENABLED=true
            - AUTORUN_LARAVEL_MIGRATION_ISOLATION=true
            - APP_ENV
            - APP_KEY
            - APP_URL
            - APP_DEBUG
            - APP_LOCALE
            - APP_FALLBACK_LOCALE
            - APP_FAKER_LOCALE
            - APP_MAINTENANCE_DRIVER
            - APP_MAINTENANCE_STORE
            - BCRYPT_ROUNDS
            - LOG_CHANNEL
            - LOG_STACK
            - LOG_DEPRECATIONS_CHANNEL
            - LOG_LEVEL
            - DB_CONNECTION
            - DB_URL
            - SESSION_DRIVER
            - SESSION_LIFETIME
            - SESSION_ENCRYPT
            - SESSION_PATH
            - SESSION_DOMAIN
            - BROADCAST_CONNECTION
            - FILESYSTEM_DISK
            - QUEUE_CONNECTION
            - CACHE_STORE
            - CACHE_PREFIX
            - REDIS_CLIENT
            - REDIS_URL
            - MAIL_MAILER
            - MAIL_HOST
            - MAIL_PORT
            - MAIL_USERNAME
            - MAIL_PASSWORD
            - MAIL_ENCRYPTION
            - MAIL_FROM_ADDRESS
            - MAIL_FROM_NAME
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - AWS_BUCKET
            - AWS_USE_PATH_STYLE_ENDPOINT
            - AWS_URL
            - AWS_ENDPOINT
            - VITE_APP_NAME
            - GOOGLE_CLIENT_ID
            - GOOGLE_CLIENT_SECRET
            - GOOGLE_CALLBACK_URL
            - CURRENCY_API_KEY
            - WORKSPACES_PROFILE_PHOTO_DISK
            - SSR_URL=http://ssr:13714
        networks:
            - app_network
    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["php", "/var/www/html/artisan", "queue:work", "--sleep=3", "--tries=3", "--max-time=3600"]
        stop_signal: SIGTERM # Set this for graceful shutdown if you're using fpm-apache or fpm-nginx
        healthcheck:
            # This is our native healthcheck script for the queue
            test: ["CMD", "healthcheck-queue"]
            start_period: 10s
        volumes:
            - "./storage:/var/www/html/storage"
        environment:
            PHP_FPM_POOL_NAME: app_queue
    ssr:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["php", "/var/www/html/artisan", "inertia:start-ssr", "--runtime=bun"]
        ports:
            - "13714:13714"
        volumes:
            - "./storage:/var/www/html/storage"
        environment:
            PHP_FPM_POOL_NAME: app_ssr
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
