// This file is generated by Vagebond\Runtype
// App\Http\Resources\BankConnectionResource
export type BankConnectionResourceType = {
    id: string;
    institutionName: string;
    institutionLogoUrl: string;
    providerType: { name: string; value: string };
    isActive: boolean;
};
// App\Http\Resources\LanguageResource
export type LanguageResourceType = any;
// App\Http\Resources\AccountResource
export type AccountResourceType = {
    id: string;
    name: string;
    description: unknown;
    currencyCode: string;
    initialBalance: string;
    currentBalance: string;
    isDefault: boolean;
    externalId: string;
    connection: BankConnectionResourceType;
};
