// This file is generated by Vagebond\Runtype
// App\Http\Resources\BankConnectionResource
export type BankConnectionResourceType = {
    id: string;
    institutionName: string;
    institutionLogoUrl: string;
    providerType: { name: string; value: string };
    status: { name: string; value: string };
};
// App\Http\Resources\LanguageResource
export type LanguageResourceType = any;
// App\Http\Resources\AccountResource
export type AccountResourceType = {
    id: string;
    name: string;
    description: unknown;
    currencyCode: string;
    initialBalance: string;
    currentBalance: string;
    isDefault: boolean;
    externalId: string;
    connection: BankConnectionResourceType;
};
// App\Http\Resources\TransactionResource
export type TransactionResourceType = {
    id: string;
    name: string;
    type: string;
    baseAmount: unknown;
    baseCurrency: unknown;
    currencyRate: unknown;
    amount: string;
    currency: string;
    isRecurring: boolean;
    isManual: boolean;
    datedAt: string;
};
