// This file is generated by Vagebond\Runtype
// App\Http\Resources\LanguageResource
export type LanguageResourceType = any;
// App\Http\Resources\AccountResource
export type AccountResourceType = {
    id: number;
    name: string;
    description: unknown;
    currencyCode: string;
    initialBalance: string;
    currentBalance: string;
    isDefault: boolean;
    publicId: string;
    externalId: string;
    institution: { logoUrl: string; status: string };
};
